<?php

namespace Wc\GameBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Stage
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Stage extends EntityRepository
{
}
