<?php

namespace Wc\UserBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Wc\UserBundle\Entity;

/**
 * Top
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
abstract class Top extends EntityRepository
{
    
    private function query()
    {
        $q = $this->createQueryBuilder('b');
        return $q
            ->addSelect($q->expr()->count('b.user') . ' AS num')
            ->addGroupBy('b.user')
            ->addOrderBy('num', 'DESC')
        ;
    }
    
    public function bets()
    {
        return $this->query()->getQuery()->getResult();
    }
    
    public function corrects()
    {
        return $this->query()
            ->where('b.correct = ?1')
            ->setParameter(1, 1)
            ->getQuery()
            ->getResult()
        ;
    }
    
    public function wrongs()
    {
        return $this->query()
            ->where('b.correct = ?1')
            ->setParameter(1, 0)
            ->getQuery()
            ->getResult()
        ;
    }
    
    public function spend()
    {
        $q = $this->createQueryBuilder('b');
        $q
            ->addSelect('SUM(b.points) AS num')
            ->addGroupBy('b.user')
            ->addOrderBy('num', 'DESC')
        ;
        
        return $q
            ->getQuery()
            ->getResult()
        ;
        
    }
    
}
