<?php

namespace Wc\UserBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Wc\UserBundle\Entity;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class User extends EntityRepository
{
    public function toplist()
    {
        $users = $this->findBy(
            array(),
            array('points' => 'desc')
        );
        
        foreach($users as $key => $u) {
            /** @var Entity\User $u */
            if ($u->getBets()->count() <= 0) {
                unset($users[$key]);
            }
        }
        
        return $users;
        
    }
}
